#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;

use lib '.';
use ProtoTTS;



Getopt::Long::Configure 'pass_through', 'noauto_abbrev';

my %args = ();

GetOptions
    \%args,
    'message|m:s',
    'voice|v:s',
    'list-voices:s',
    'list-langs',
    'help|h'
;

ProtoTTS->Display_Banner;

my $prototts = ProtoTTS->new;

if ( $args{'list-langs'} ){
    $prototts->list_langs;
    exit;
}

if ( $args{'list-voices'} ){
    $prototts->list_voices($args{'list-voices'});
    exit;
}

if ( $args{help} ){
    ProtoTTS->Display_Options;
    exit;
}

if ( $args{message} ){
    $prototts->set_message($args{message});
    $prototts->set_voice($args{voice}) if $args{voice};
    $prototts->play;
    exit;
}

print "USAGE: ./prototts [OPTIONS]\n";
exit 1;
